[package]
name = "yoda-taller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test_fixture = []

[dependencies]
anyhow = "1.0.70"
axum = "0.6.15"
reqwest = { version = "0.11.16", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.160", features = ["derive"] }
thiserror = "1.0.40"
tracing = "0.1.37"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread", "signal"] }
serde_yaml = "0.9.21"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
axum-tracing-opentelemetry = { version = "0.10", features = ["jaeger", "otlp"] }

tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-log = "0.1.3"
tracing-bunyan-formatter = "0.3.7"
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio"] }
tracing-opentelemetry = "0.18.0"

[dev-dependencies]
yoda-taller = { path = ".", features = ["test_fixture"]}
serde_json = "1.0.95"
wiremock = "0.5.18"
once_cell = "1.17.1"
