[package]
name = "yoda-taller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swapi = { path = "../swapi" }
reqwest = { version = "0.11.11", features = ["json"] }

[dev-dependencies]
swapi_mock = { path = "../swapi_mock" }
wiremock = "0.5.13"
tokio = { version = "1.19.2", features = ["macros"] }
