[package]
name = "yoda-taller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test_fixture = []

[dependencies]
anyhow = "1.0.58"
axum = "0.5.11"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"
tracing = "0.1.35"
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread"] }
serde_yaml = "0.9.10"
traces ={ path = "../traces" }
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
axum-tracing-opentelemetry = { version = "0.4", features = ["jaeger", "otlp"] }

[dev-dependencies]
yoda-taller = { path = ".", features = ["test_fixture"]}
serde_json = "1.0.82"
wiremock = "0.5.13"
