[package]
name = "yoda-taller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test_fixture = []

[dependencies]
anyhow = "1.0.65"
axum = "0.5.16"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.145", features = ["derive"] }
thiserror = "1.0.37"
tracing = "0.1.36"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
serde_yaml = "0.9.13"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
axum-tracing-opentelemetry = { version = "0.4", features = ["jaeger", "otlp"] }

tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
tracing-log = "0.1.3"
tracing-bunyan-formatter = "0.3.3"
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio"] }
tracing-opentelemetry = "0.18.0"

[dev-dependencies]
yoda-taller = { path = ".", features = ["test_fixture"]}
serde_json = "1.0.85"
wiremock = "0.5.14"
once_cell = "1.15.0"
