[package]
name = "workshop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
axum = "0.5.13"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.31"
tracing = "0.1.35"
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread"] }
serde_yaml = "0.9.10"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
axum-tracing-opentelemetry = { version = "0.4", features = ["jaeger", "otlp"] }

tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
tracing-log = "0.1.3"
tracing-bunyan-formatter = "0.3.3"
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio"] }
tracing-opentelemetry = "0.17.4"

[dev-dependencies]
serde_json = "1.0.82"
wiremock = "0.5.13"
once_cell = "1.13.0"
